# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar.yaml
  - model: cifar.yaml
  - paths: default.yaml
  - trainer: default.yaml

task_name: "train"

train: True

test: True

compile: False

ckpt_path: null

seed: 23